import React, { useState } from 'react';
import type { AttentionError } from '../lib/api';

const labels:Record<string,string> = {telegram:'Telegram',llm:'LLM',google_sheets:'Google Sheets',configuration:'Конфигурация',source:'Источник',pipeline:'Pipeline',other:'Другое'};
const nextSteps:Record<string,string> = {telegram:'Проверьте статус процесса и журнал Telegram.',llm:'Откройте логи LLM и проверьте доступность интеграции.',google_sheets:'Откройте логи Google Sheets и права service account.',configuration:'Проверьте сохранённые настройки и примените restart.',source:'Проверьте username источника и повторите проверку.',pipeline:'Откройте логи обработки для безопасных деталей.',other:'Откройте логи и проверьте состояние процесса.'};
export function AttentionPanel({ errors, loading, onResolve, onOpenErrors, showEmpty=false }: {errors:AttentionError[];loading:boolean;onResolve:(id:string)=>Promise<void>;onOpenErrors?:()=>void;showEmpty?:boolean}) {
  const [opened,setOpened] = useState<string>();
  if (!loading && !errors.length) return showEmpty ? <div className="empty">Активных ошибок нет. Разрешённые ошибки не смешиваются с этим списком.</div> : null;
  return <article className="card span-12 attention" aria-labelledby="attention-title"><div className="section-title"><div><h2 id="attention-title">Требуют внимания</h2><p className="muted">Показаны только активные безопасно очищенные ошибки.</p></div>{onOpenErrors&&<button className="button secondary" onClick={onOpenErrors}>Все активные ошибки</button>}</div>{loading ? <p className="muted">Проверяем ошибки…</p> : <div className="stack">{errors.map((item)=><div className="attention-item" key={item.id}><div><strong>{labels[item.component] ?? item.component}</strong> <span className="status">{item.status==='repeating'?'повторяется':'новая'}</span><p>{item.summary}</p><p className="muted"><strong>Следующее действие:</strong> {nextSteps[item.component]??nextSteps.other}</p><small className="muted">{new Date(item.last_seen_at).toLocaleString('ru-RU')}{item.count > 1 ? ` · повторов: ${item.count}` : ''}</small>{opened===item.id && <pre className="technical">{item.details}</pre>}</div><div className="actions"><button className="button secondary" aria-expanded={opened===item.id} onClick={()=>setOpened(opened===item.id?undefined:item.id)}>Безопасные детали</button><button className="button secondary" onClick={()=>void onResolve(item.id)}>Пометить решённой</button></div></div>)}</div>}</article>;
}
