'use client';

import React, { useEffect, useState } from 'react';
import { api, type LogsPage } from '../lib/api';

export function LogsPanel({onBack}:{onBack:()=>void}) {
  const [data,setData] = useState<LogsPage>(); const [error,setError]=useState(''); const [loading,setLoading]=useState(true);
  const [level,setLevel]=useState(''); const [component,setComponent]=useState(''); const [period,setPeriod]=useState('7d'); const [search,setSearch]=useState(''); const [offset,setOffset]=useState(0);
  const load=async(nextOffset=offset)=>{setLoading(true);setError('');try{setData(await api.logs({level,component,period,search,offset:nextOffset,limit:30}));setOffset(nextOffset)}catch(reason){setError(reason instanceof Error?reason.message:'Сервис логов недоступен')}finally{setLoading(false)}};
  useEffect(()=>{void load(0)},[level,component,period]);
  return <section className="screen"><div className="section-title"><div><button className="link" onClick={onBack}>← Дашборд</button><h1>Логи</h1><p className="muted">Последние очищенные записи приложения. Токены, пароли и session-данные маскируются до выдачи API.</p></div><button className="button secondary" onClick={()=>void load(0)}>{loading?'Обновляем…':'Обновить'}</button></div><div className="filters"><label>Уровень<select aria-label="Уровень лога" value={level} onChange={event=>setLevel(event.target.value)}><option value="">Все</option><option>INFO</option><option>WARNING</option><option>ERROR</option></select></label><label>Компонент<select aria-label="Компонент лога" value={component} onChange={event=>setComponent(event.target.value)}><option value="">Все</option><option value="telegram">Telegram</option><option value="llm">LLM</option><option value="google_sheets">Google Sheets</option><option value="configuration">Конфигурация</option><option value="source">Источник</option><option value="pipeline">Pipeline</option></select></label><label>Период<select aria-label="Период логов" value={period} onChange={event=>setPeriod(event.target.value)}><option value="today">Сегодня</option><option value="7d">7 дней</option><option value="all">Все доступные</option></select></label><label className="search">Поиск<input aria-label="Поиск по логам" value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>{if(event.key==='Enter') void load(0)}} /><button className="button secondary" onClick={()=>void load(0)}>Найти</button></label></div>{error?<p className="error" role="alert">Логи временно недоступны: {error}</p>:loading&&!data?<p className="muted">Загружаем логи…</p>:!data?.items.length?<div className="empty">За выбранный период безопасных логов пока нет.</div>:<><div className="log-list">{data.items.map((item,index)=><article className="log-entry" key={`${item.at}-${index}`}><time>{new Date(item.at).toLocaleString('ru-RU')}</time><span className={`log-level ${item.level.toLowerCase()}`}>{item.level}</span><span className="log-component">{item.component}</span><p>{item.message}</p></article>)}</div><div className="pagination"><span className="muted">Показано {data.offset+1}–{Math.min(data.offset+data.items.length,data.total)} из {data.total}</span><button className="button secondary" disabled={!offset||loading} onClick={()=>void load(Math.max(0,offset-30))}>Назад</button><button className="button secondary" disabled={loading||offset+30>=data.total} onClick={()=>void load(offset+30)}>Далее</button></div></>}</section>;
}
