'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { premiumApi, type PremiumCapabilities, type PremiumParams, type PremiumRun, type PremiumResults } from '../lib/api';
import { ConfirmAction } from './confirm-action';

export const premiumStates:Record<string,string> = {queued:'В очереди',running:'Выполняется',quota_check:'Проверка бесплатной квоты',searching:'Поиск публичных постов',analyzing:'Анализ вакансий',flood_wait:'Ожидание Telegram FloodWait',llm_retry:'Повтор анализа',completed:'Завершён',completed_with_errors:'Завершён с частичными ошибками',failed:'Ошибка поиска',cancelled:'Отменён',pending:'Ожидает анализа',accepted:'Подходит',review:'Нужна проверка',rejected:'Отклонён',duplicate:'Дубликат',saved:'Сохранён',published:'Опубликован',error:'Ошибка'};
const metricLabels:Record<string,string> = {found:'Найдено',invalid:'Неверный источник / контент',old:'Старые',prefilter_rejected:'Отсечено фильтром',duplicates:'Дубликаты',llm_analyzed:'Вызовы Mistral',accepted:'Принято',rejected:'Отклонено',review:'На проверку',saved:'Сохранено',published:'Опубликовано',errors:'Ошибки',rate_limit_waits:'Ожидания лимита',duration_seconds:'Длительность, сек.'};
const actionLabels:Record<string,string> = {save:'Сохранить',publish:'Опубликовать',reject:'Отклонить',mark_duplicate:'Отметить дубликатом',add_public_source:'Добавить источник'};
const reasonLabels:Record<string,string> = {premium_required:'Для поиска требуется Telegram Premium.',telegram_auth_required:'Требуется авторизация Telegram-сессии.',free_quota_exhausted:'Бесплатная квота исчерпана. Stars не списываются.',telegram_or_search_failure:'Telegram не выполнил поиск. Проверьте авторизацию и Premium.',publisher_not_configured:'Candidate publisher не настроен.',search_interrupted:'Поиск прерван перезапуском; создайте новый запуск.',llm_budget_exhausted:'Достигнут лимит вызовов Mistral.',llm_failed:'Не удалось получить корректный анализ.',delivery_uncertain:'Доставка не определена. Повторная отправка заблокирована.',source_added_restart_required:'Источник добавлен. Требуется перезапуск мониторинга.'};
const active = (run?:PremiumRun) => !!run && ['queued','running'].includes(run.status);
const date = (value:string|null|undefined) => value ? new Date(value).toLocaleString('ru-RU') : '—';

export function PremiumSearchPanel({capabilities}:{capabilities:PremiumCapabilities|null}) {
  const [params,setParams]=useState<PremiumParams>({query:'',track:'go',mode:'preview',result_limit:50,period_days:7,include_review:true});
  const [runs,setRuns]=useState<PremiumRun[]>([]);const [id,setId]=useState('');const [run,setRun]=useState<PremiumRun>();const [results,setResults]=useState<PremiumResults>();
  const [filter,setFilter]=useState('');const [offset,setOffset]=useState(0);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);
  const [confirmation,setConfirmation]=useState<{title:string;description:string;execute:()=>Promise<void>}|null>(null);
  const mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  const refreshRuns=useCallback(async()=>{const list=await premiumApi.runs();if(mounted.current){setRuns(list.items);setId(value=>value||list.items[0]?.search_run_id||'');}},[]);
  useEffect(()=>{if(capabilities)void refreshRuns().catch(()=>setError('Не удалось загрузить запуски'));},[capabilities,refreshRuns]);
  useEffect(()=>{
    if(!capabilities||!id)return;
    let disposed=false;let timer:ReturnType<typeof setTimeout>|undefined;
    const load=async()=>{setLoading(true);try{const [next,page]=await Promise.all([premiumApi.run(id),premiumApi.results(id,filter,offset)]);if(disposed)return;setRun(next);setResults(page);setError('');
      // Keep polling while this run or a manual action is in progress.
      if(active(next)||page.items.some(item=>['queued','running'].includes(item.action_state)))timer=setTimeout(()=>void load(),2000);
    }catch(reason){if(!disposed){setError(reason instanceof Error?reason.message:'Ошибка загрузки');timer=setTimeout(()=>void load(),2000);}}finally{if(!disposed)setLoading(false);}};
    void load();return()=>{disposed=true;if(timer)clearTimeout(timer);};
  },[capabilities,id,filter,offset,notice]);
  if(!capabilities)return <section className="card"><h1>Premium поиск</h1><p>Экспериментальный поиск отключён.</p></section>;
  const confirmCreate=()=>{const query=params.query.trim().replace(/\s+/g,' ');if(query.length<3||query.length>160||!Number.isInteger(params.result_limit)||params.result_limit<1||params.result_limit>100||!Number.isInteger(params.period_days)||params.period_days<1||params.period_days>30){setError('Укажите запрос от 3 до 160 символов, 1–100 результатов и 1–30 дней.');return;}setConfirmation({title:'Запустить Premium поиск',description:`${query} · ${params.result_limit} результатов · ${params.period_days} дней. До 20 вызовов Mistral. ${params.mode==='preview'?'Предпросмотр без записи в таблицы.':params.mode==='save'?'Запись в оба листа Google Sheets.':'Запись в таблицы и отправка карточек Candidate Bot.'} Telegram Stars не используются.`,execute:async()=>{const next=await premiumApi.create({...params,query});setId(next.search_run_id);setRun(next);setOffset(0);await refreshRuns();}});};
  const action=(resultId:string,name:string)=>setConfirmation({title:actionLabels[name],description:name==='add_public_source'?'Публичный канал будет добавлен в реестр. Для мониторинга потребуется перезапуск.':name==='publish'?'Сначала сохраним в обе таблицы, затем отправим карточку Candidate Bot.':name==='save'?'Вакансия будет записана в оба листа Google Sheets. Неуверенный анализ подтверждается вручную.':'Решение будет сохранено в истории. Исходный пост останется доступен.',execute:async()=>{await premiumApi.action(resultId,name);setNotice(`Действие поставлено в очередь: ${actionLabels[name]} · ${Date.now()}`);}});
  const execute=async()=>{if(!confirmation||busy)return;setBusy(true);setError('');try{await confirmation.execute();setConfirmation(null);}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось выполнить действие');setConfirmation(null);}finally{setBusy(false);}};
  return <section className="screen premium-search"><div className="section-title"><div><h1>Premium поиск</h1><p className="muted">Экспериментальный поиск публичных каналов, включая каналы вне подписок. Полноту и порядок определяет Telegram.</p></div></div>
    {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice.replace(/ · \d+$/,'')}</p>}
    <form className="card premium-form" onSubmit={event=>{event.preventDefault();confirmCreate();}}>
      <label>Поисковый запрос<input value={params.query} minLength={3} maxLength={160} required onChange={event=>setParams({...params,query:event.target.value})}/></label>
      <label>Трек<select value={params.track} onChange={event=>setParams({...params,track:event.target.value})}>{capabilities.tracks.map(track=><option key={track.key} value={track.key}>{track.label}</option>)}</select></label>
      <label>Результатов<input type="number" min={1} max={100} required value={params.result_limit} onChange={event=>setParams({...params,result_limit:Number(event.target.value)})}/></label>
      <label>Возраст, дней<input type="number" min={1} max={30} required value={params.period_days} onChange={event=>setParams({...params,period_days:Number(event.target.value)})}/></label>
      <label>Режим<select value={params.mode} onChange={event=>setParams({...params,mode:event.target.value})}><option value="preview">Предпросмотр</option><option value="save">Сохранить</option><option value="save_publish" disabled={!capabilities.publisher_configured}>Сохранить и опубликовать</option></select></label>
      <label className="checkbox"><input type="checkbox" checked={params.include_review} onChange={event=>setParams({...params,include_review:event.target.checked})}/>Показывать неуверенные результаты по умолчанию</label>
      <p className="muted">Go-вакансии с неуверенной или противоречивой оценкой доступны для ручной проверки. В предпросмотре выберите подходящие и нажмите «Опубликовать». Автоматический отбор в других режимах по-прежнему требует 90%. Максимум 20 обращений к Mistral за запуск.</p><button className="button" disabled={busy}>Запустить поиск</button>
    </form>
    <div className="card"><label>История запусков<select value={id} onChange={event=>{setId(event.target.value);setOffset(0);setRun(undefined);}}><option value="">Выберите запуск</option>{runs.map(item=><option key={item.search_run_id} value={item.search_run_id}>{item.query} · {date(item.created_at)}</option>)}</select></label>{!runs.length&&<p>Поисков ещё нет. Начните с предпросмотра.</p>}</div>
    {run&&<><section className="card" aria-label="Ход поиска"><h2>{run.query}</h2><p role="status">{run.cancel_requested&&active(run)?'Отмена запрошена…':premiumStates[active(run)&&run.phase!=='queued'?run.phase:run.status]||run.status}{loading?' · обновление…':''}</p>{run.retry_at&&active(run)&&<p>Повтор после {date(run.retry_at)}</p>}{run.error_reason&&<p className="error">{reasonLabels[run.error_reason]||run.error_reason}</p>}{run.quota.remains!==undefined&&<p>Бесплатных запросов: {run.quota.remains}. Сброс: {date(run.quota.reset_at)}</p>}
      {active(run)&&<button className="button secondary" disabled={!!run.cancel_requested} onClick={()=>setConfirmation({title:'Отменить поиск',description:'Уже сохранённые записи останутся. Текущий сетевой запрос может завершиться до отмены.',execute:async()=>{setRun(await premiumApi.cancel(id));setNotice(`Отмена запрошена · ${Date.now()}`);}})}>Отменить поиск</button>}
      <dl className="premium-metrics">{Object.entries(metricLabels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{run.metrics[key]??0}</dd></div>)}</dl></section>
      <section className="card"><div className="section-title"><h2>Результаты ({results?.total??0})</h2><label>Статус<select value={filter} onChange={event=>{setFilter(event.target.value);setOffset(0);}}><option value="">По умолчанию</option>{['pending','accepted','review','rejected','duplicate','saved','published','error','cancelled'].map(value=><option key={value} value={value}>{premiumStates[value]}</option>)}</select></label></div>
        {!results?.items.length&&<p>Результатов для выбранного фильтра пока нет.</p>}
        <div className="premium-results">{results?.items.map(item=><article className="card" key={item.result_id}><h3>{item.title||'Пост без извлечённого названия'}</h3><p>{item.company||'Компания не определена'} · {premiumStates[item.status]}</p><p>{item.summary}</p><p className="muted">{item.channel_name||'Источник не прошёл проверку'} · {date(item.published_at)}</p><p>Уверенность: {item.confidence??'—'}% · Go: {item.go_role_strength||'—'} · Язык: {item.language||'—'}</p><p>{reasonLabels[item.decision_reason]||item.decision_reason}</p>{item.group_id&&<p>Группа: {item.group_id}</p>}{item.post_link&&<a href={item.post_link} target="_blank" rel="noreferrer">Открыть пост в Telegram</a>}
          {['queued','running'].includes(item.action_state)&&<p role="status">Действие {item.action_state==='queued'?'в очереди':'выполняется'}…</p>}{item.action_error&&<p role="alert" className="error">{reasonLabels[item.action_error]||'Не удалось выполнить действие'}</p>}
          <div className="actions">{Object.entries(actionLabels).filter(([name])=>name==='add_public_source'?!!item.channel_username:name==='publish'?['accepted','review','saved'].includes(item.status):name==='save'?['accepted','review'].includes(item.status)&&item.can_persist:!['saved','published','pending'].includes(item.status)).map(([name,label])=><button className={name==='publish'?'button':'button secondary'} key={name} disabled={(name==='publish'&&(!capabilities.publisher_configured||!item.can_persist))||busy||['queued','running'].includes(item.action_state)} onClick={()=>action(item.result_id,name)}>{label}</button>)}</div>
          {['accepted','review','saved'].includes(item.status)&&(!capabilities.publisher_configured||!item.can_persist)&&<p className="muted">{!capabilities.publisher_configured?'Публикация недоступна: Candidate Bot не настроен.':item.delivery_state==='sending'?reasonLabels.delivery_uncertain:'Публикация недоступна: нет сохранённого анализа или истёк срок хранения текста.'}</p>}
        </article>)}</div><div className="actions"><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Назад</button><button className="button secondary" disabled={offset+25>=(results?.total??0)} onClick={()=>setOffset(offset+25)}>Далее</button></div>
      </section></>}
    {confirmation&&<ConfirmAction title={confirmation.title} description={busy?'Выполняется…':confirmation.description} onConfirm={()=>void execute()} onCancel={()=>{if(!busy)setConfirmation(null);}}/>}
  </section>;
}
