import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { PremiumSearchPanel, premiumStates } from './premium-search-panel';
import { premiumApi, type PremiumRun, type PremiumResult } from '../lib/api';

vi.mock('../lib/api',()=>({premiumApi:{runs:vi.fn(),run:vi.fn(),results:vi.fn(),create:vi.fn(),cancel:vi.fn(),action:vi.fn()}}));
const capabilities={enabled:true,publisher_configured:true,tracks:[{key:'go',label:'Go / Golang',confidence_threshold:90}]};
const run:PremiumRun={search_run_id:'run1',query:'Golang',track:'go',mode:'preview',status:'completed',phase:'finished',cancel_requested:0,retry_at:null,error_reason:null,quota:{remains:5},metrics:{found:4,llm_analyzed:2},include_review:true,created_at:'2026-09-11T12:00:00Z'};
const result:PremiumResult={result_id:'r1',post_link:'https://t.me/public_jobs/1',channel_username:'public_jobs',channel_name:'Public jobs',published_at:'2026-09-11T12:00:00Z',title:'Go developer',company:'Company',summary:'Backend role',status:'accepted',decision_reason:'llm_accepted',confidence:95,go_role_strength:'primary',language:'ru',group_id:null,action_state:'idle',action_error:null,delivery_state:'pending'};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(premiumApi.runs).mockResolvedValue({items:[run]});vi.mocked(premiumApi.run).mockResolvedValue(run);vi.mocked(premiumApi.results).mockResolvedValue({items:[result],total:1,offset:0,limit:25});vi.mocked(premiumApi.create).mockResolvedValue(run);vi.mocked(premiumApi.action).mockResolvedValue({item:{...result,action_state:'queued'},restart_required:false});});
afterEach(()=>{cleanup();vi.useRealTimers();});

describe('Premium search',()=>{
  it('does not load anything when disabled',()=>{render(<PremiumSearchPanel capabilities={null}/>);expect(screen.getByText('Экспериментальный поиск отключён.')).toBeInTheDocument();expect(premiumApi.runs).not.toHaveBeenCalled();});
  it('shows empty history',async()=>{vi.mocked(premiumApi.runs).mockResolvedValue({items:[]});render(<PremiumSearchPanel capabilities={capabilities}/>);expect(await screen.findByText('Поисков ещё нет. Начните с предпросмотра.')).toBeInTheDocument();});
  it('validates a form and confirms before queueing',async()=>{render(<PremiumSearchPanel capabilities={capabilities}/>);const input=screen.getByLabelText('Поисковый запрос');fireEvent.change(input,{target:{value:'ab'}});fireEvent.submit(input.closest('form')!);expect(screen.getByRole('alert')).toHaveTextContent('Укажите запрос');expect(premiumApi.create).not.toHaveBeenCalled();fireEvent.change(input,{target:{value:'Go jobs'}});fireEvent.submit(input.closest('form')!);expect(screen.getByRole('dialog')).toBeInTheDocument();expect(premiumApi.create).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Подтвердить'}));await waitFor(()=>expect(premiumApi.create).toHaveBeenCalledWith(expect.objectContaining({query:'Go jobs',result_limit:50,period_days:7})));});
  it.each(['queued','quota_check','searching','analyzing','flood_wait','completed','completed_with_errors','failed','cancelled'])('shows %s state',async(state)=>{vi.mocked(premiumApi.run).mockResolvedValue({...run,status:['quota_check','searching','analyzing','flood_wait'].includes(state)?'running':state,phase:state});render(<PremiumSearchPanel capabilities={capabilities}/>);expect(await screen.findByText(premiumStates[state],{exact:false,selector:'p[role=status]'})).toBeInTheDocument();});
  it('shows quota and reset and aggregate metrics',async()=>{vi.mocked(premiumApi.run).mockResolvedValue({...run,status:'failed',error_reason:'free_quota_exhausted',quota:{remains:0,reset_at:'2026-09-12T00:00:00Z'}});render(<PremiumSearchPanel capabilities={capabilities}/>);expect(await screen.findByText('Бесплатная квота исчерпана. Stars не списываются.')).toBeInTheDocument();expect(screen.getByText(/Бесплатных запросов: 0/)).toBeInTheDocument();expect(screen.getByText('Вызовы Mistral')).toBeInTheDocument();expect(screen.getByText('4')).toBeInTheDocument();});
  it('filters and confirms manual actions without optimistic publication',async()=>{render(<PremiumSearchPanel capabilities={capabilities}/>);await screen.findByText('Go developer');fireEvent.change(screen.getByLabelText('Статус'),{target:{value:'review'}});await waitFor(()=>expect(premiumApi.results).toHaveBeenCalledWith('run1','review',0));fireEvent.click(screen.getByRole('button',{name:'Сохранить'}));expect(premiumApi.action).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Подтвердить'}));await waitFor(()=>expect(premiumApi.action).toHaveBeenCalledWith('r1','save'));expect(await screen.findByText('Действие поставлено в очередь: Сохранить')).toBeInTheDocument();expect(screen.queryByText('Опубликован',{selector:'p'})).not.toBeInTheDocument();});
  it('disables pending actions and unavailable publishing',async()=>{vi.mocked(premiumApi.results).mockResolvedValue({items:[{...result,action_state:'queued'}],total:1,offset:0,limit:25});render(<PremiumSearchPanel capabilities={{...capabilities,publisher_configured:false}}/>);expect(await screen.findByText('Действие в очереди…')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Сохранить'})).toBeDisabled();expect(screen.queryByRole('button',{name:'Сохранить и опубликовать'})).not.toBeInTheDocument();});
  it('shows empty filtered results and cancelling',async()=>{vi.mocked(premiumApi.run).mockResolvedValue({...run,status:'running',phase:'analyzing',cancel_requested:1});vi.mocked(premiumApi.results).mockResolvedValue({items:[],total:0,offset:0,limit:25});render(<PremiumSearchPanel capabilities={capabilities}/>);expect(await screen.findByText(/Отмена запрошена/)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Отменить поиск'})).toBeDisabled();expect(screen.getByText('Результатов для выбранного фильтра пока нет.')).toBeInTheDocument();});
  it('polls every two seconds and cleans up on unmount',async()=>{vi.useFakeTimers();vi.mocked(premiumApi.run).mockResolvedValue({...run,status:'running',phase:'analyzing'});let view:ReturnType<typeof render>;await act(async()=>{view=render(<PremiumSearchPanel capabilities={capabilities}/>);});expect(premiumApi.run).toHaveBeenCalledTimes(1);await act(async()=>{await vi.advanceTimersByTimeAsync(2000);});expect(premiumApi.run).toHaveBeenCalledTimes(2);view!.unmount();await act(async()=>{await vi.advanceTimersByTimeAsync(6000);});expect(premiumApi.run).toHaveBeenCalledTimes(2);});
  it('shows network failures without removing the form',async()=>{vi.mocked(premiumApi.run).mockRejectedValue(new Error('Соединение прервано'));render(<PremiumSearchPanel capabilities={capabilities}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Соединение прервано');expect(screen.getByRole('button',{name:'Запустить поиск'})).toBeEnabled();});
});
