'use client';

import React, { useEffect, useState } from 'react';
import { ConfirmAction } from './confirm-action';
import { api, type Prompt } from '../lib/api';

export function PromptEditor({onBack}:{onBack:()=>void}) {
  const [prompt,setPrompt]=useState<Prompt>(); const [value,setValue]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [confirmReset,setConfirmReset]=useState(false);
  const load=async()=>{try{const result=await api.prompt();setPrompt(result);setValue(result.instructions)}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось загрузить инструкции')}};
  useEffect(()=>{void load()},[]);
  const save=async()=>{const next=value.trim();if(next.length<20||next.length>12000){setError('Инструкции должны содержать от 20 до 12000 символов');return}if(/(?:api[_ -]?key|token|password|secret|authorization|cookie|credential)\s*[:=]|\bsk-[a-z0-9_-]{10,}|bearer\s+[a-z0-9._-]{12,}/i.test(next)){setError('Инструкции не должны содержать секреты или токены');return}setSaving(true);setError('');try{const result=await api.savePrompt(next);setPrompt({...prompt!,...result,default_instructions:prompt?.default_instructions??'',variables:[]});}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось сохранить инструкции')}finally{setSaving(false)}};
  const reset=async()=>{try{const result=await api.resetPrompt();setValue(result.instructions);setPrompt({...prompt!,...result,default_instructions:prompt?.default_instructions??'',variables:[]});setConfirmReset(false)}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось восстановить инструкции');setConfirmReset(false)}};
  return <section className="screen"><div className="section-title"><div><button className="link" onClick={onBack}>← Дашборд</button><h1>LLM: инструкции извлечения вакансий</h1><p className="muted">Изменяются только инструкции. Строгая JSON-схема и Pydantic-проверка остаются фиксированными. Новое значение вступит в силу после перезапуска бота.</p></div></div>{error&&<p className="error" role="alert">{error}</p>}{!prompt?<p className="muted">Загружаем редактор…</p>:<><label className="field">Инструкции для LLM<textarea aria-label="Инструкции для LLM" value={value} onChange={event=>setValue(event.target.value)} rows={22} /><span className="muted">{value.trim().length} / 12000 символов. Секреты и токены запрещены.</span></label>{prompt.variables.length>0&&<p>Доступные переменные: {prompt.variables.join(', ')}</p>}<div className="actions"><button className="button" onClick={()=>void save()} disabled={saving}>{saving?'Сохраняем…':'Сохранить инструкции'}</button><button className="button secondary" onClick={()=>setConfirmReset(true)}>Восстановить значение по умолчанию</button></div></>}{confirmReset&&<ConfirmAction title="Восстановить инструкции" description="Пользовательские инструкции будут заменены штатным безопасным значением. Строгая схема ответа останется без изменений." onConfirm={reset} onCancel={()=>setConfirmReset(false)} />}</section>;
}
