'use client';

import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { ConfirmAction } from './confirm-action';
import { api, type Source } from '../lib/api';

export function SourcesPanel({onBack,onChanged}:{onBack:()=>void;onChanged:()=>Promise<void>}) {
  const [sources,setSources]=useState<Source[]>([]); const [query,setQuery]=useState(''); const [identifier,setIdentifier]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [pendingDelete,setPendingDelete]=useState<Source>();
  const load=async()=>{setLoading(true);setError('');try{const result=await api.sources();setSources(result.items)}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось загрузить источники')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>sources.filter(item=>`${item.label} ${item.identifier??''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())),[sources,query]);
  const add=async(event:FormEvent)=>{event.preventDefault();setError('');const compact=identifier.trim();if(!/^(?:https?:\/\/)?(?:t\.me|telegram\.me)\/[A-Za-z0-9_]+\/?$|^@[A-Za-z0-9_]+$|^[A-Za-z0-9_]+$/.test(compact)){setError('Введите публичный @username или ссылку t.me/username');return}try{await api.addSource(compact);setIdentifier('');await load();await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось добавить источник')}};
  const toggle=async(item:Source)=>{setError('');try{await api.changeSource(item.token,!item.enabled);await load();await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось изменить источник')}};
  const remove=async()=>{if(!pendingDelete)return;try{await api.deleteSource(pendingDelete.token);setPendingDelete(undefined);await load();await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'Не удалось удалить источник');setPendingDelete(undefined)}};
  return <section className="screen"><div className="section-title"><div><button className="link" onClick={onBack}>← Дашборд</button><h1>Источники ({sources.length})</h1><p className="muted">Изменения сохраняются сразу, а подключение к Telegram применяется после подтверждённого перезапуска. Удаление не затрагивает вакансии, метрики и логи.</p></div><button className="button secondary" onClick={()=>void load()}>Обновить</button></div><form className="source-form" onSubmit={add}><label className="field">Добавить публичный источник<input aria-label="Новый источник" value={identifier} onChange={event=>setIdentifier(event.target.value)} placeholder="@go_jobs или https://t.me/go_jobs" required /></label><button className="button">Добавить источник</button></form>{error&&<p className="error" role="alert">{error}</p>}<label className="field search-field">Поиск источника<input aria-label="Поиск источников" value={query} onChange={event=>setQuery(event.target.value)} /></label>{loading?<p className="muted">Загружаем источники…</p>:!filtered.length?<div className="empty">Источники по этому запросу не найдены.</div>:<div className="source-grid">{filtered.map(item=><article className="card source-card" key={item.token}><div><h2>{item.label}</h2><p className="muted">{item.kind==='private'?'Приватный идентификатор скрыт':item.identifier}</p><p><span className={item.enabled?'ok':'muted'}>{item.enabled?'● Отслеживается':'● Выключен'}</span></p>{item.added_at&&<small className="muted">Добавлен: {new Date(item.added_at).toLocaleString('ru-RU')}</small>}{item.origin!=='managed'&&<small className="muted block">Источник из {item.origin==='folder'?'папки Telegram':'.env/предыдущей конфигурации'}</small>}</div><div className="actions"><button className="button secondary" onClick={()=>void toggle(item)}>{item.enabled?'Выключить':'Включить'}</button>{item.removable&&<button className="button danger" onClick={()=>setPendingDelete(item)}>Удалить</button>}</div></article>)}</div>}{pendingDelete&&<ConfirmAction title="Удалить источник" description={`Источник ${pendingDelete.label} перестанет отслеживаться после перезапуска. Исторические данные сохранятся.`} onConfirm={remove} onCancel={()=>setPendingDelete(undefined)} />}</section>;
}
