'use client';

import { useEffect, useState } from 'react';
import { ConfirmAction } from '../components/confirm-action';
import { LoginForm } from '../components/login-form';
import { SettingsForm } from '../components/settings-form';
import { api, type Settings } from '../lib/api';

type Dashboard = { settings_revision:number; channel_count:number; heartbeat?:{status?:string;updated_at?:string;queue_size?:number;received_messages?:number;keyword_matches?:number;saved_matches?:number}; operations:{at:string;event:string;action?:string}[]; secret_status:{telegram:boolean;mistral:boolean;google_sheets:boolean} };
const actionText: Record<string,[string,string]> = { restart:['Перезапустить бота','Текущая очередь будет корректно завершена, затем бот поднимется с сохранёнными настройками.'], history:['Запустить историю','Live-мониторинг временно остановится: один Telegram session нельзя использовать одновременно.'], sync_channels:['Синхронизировать папку','Бот кратко отключится от Telegram, прочитает папку и применит её состав.'] };

export default function Page() {
  const [ready,setReady]=useState(false); const [configured,setConfigured]=useState(false); const [settings,setSettings]=useState<Settings>(); const [dashboard,setDashboard]=useState<Dashboard>(); const [error,setError]=useState(''); const [pending,setPending]=useState('');
  const load = async () => { const [nextSettings,nextDashboard] = await Promise.all([api.settings(),api.dashboard()]); setSettings(nextSettings); setDashboard(nextDashboard); };
  useEffect(()=>{ api.status().then(async(status)=>{setConfigured(status.configured); if(status.authenticated) await load(); setReady(true);}).catch(()=>setReady(true)); },[]);
  const authenticated=Boolean(settings);
  if(!ready) return <main className="shell">Загружаем…</main>;
  if(!authenticated) return <LoginForm configured={configured} onLogin={async(password)=>{await api.login(password); await load();}} />;
  async function save(value:Partial<Settings>) { try { setError(''); const next=await api.save(value); setSettings(next); } catch(reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить настройки'); } }
  async function doAction() { try { await api.action(pending); setPending(''); await load(); } catch(reason) { setError(reason instanceof Error ? reason.message : 'Не удалось выполнить действие'); setPending(''); } }
  const heartbeat=dashboard?.heartbeat;
  return <main className="shell"><header className="top"><div><div className="brand">Go Radar</div><div className="muted">Безопасное управление сбором вакансий</div></div><div className="actions"><button className="button secondary" onClick={()=>document.documentElement.classList.toggle('dark')}>Тема</button><button className="button secondary" onClick={async()=>{await api.logout();setSettings(undefined)}}>Выйти</button></div></header>{error&&<p className="error" role="alert">{error}</p>}<section className="grid"><article className="card span-4"><div className={heartbeat?.status==='running'?'ok':'muted'}>{heartbeat?.status==='running'?'● Бот активен':'● Нет свежего статуса'}</div><h2>{dashboard?.channel_count??0} источников</h2><p className="muted">Конфигурация revision {dashboard?.settings_revision??0}</p></article><article className="card span-4"><h2>Интеграции</h2><p>Telegram: {dashboard?.secret_status.telegram?'настроен':'не настроен'}</p><p>Mistral: {dashboard?.secret_status.mistral?'настроен':'не настроен'}</p><p>Google Sheets: {dashboard?.secret_status.google_sheets?'настроен':'не настроен'}</p></article><article className="card span-4"><h2>Действия</h2><div className="actions"><button className="button" onClick={()=>setPending('sync_channels')}>Синхронизировать</button><button className="button secondary" onClick={()=>setPending('history')}>История</button><button className="button danger" onClick={()=>setPending('restart')}>Перезапуск</button></div></article><article className="card span-12"><h2>Telegram и фильтрация</h2>{settings&&<SettingsForm settings={settings} onSave={save}/>}<h3>Источники</h3><div className="chips">{settings?.telegram.channels.map(channel=><span className={`chip ${channel.enabled?'':'off'}`} key={channel.token}>{channel.label} · {channel.enabled?'включён':'выключен'}</span>)}</div></article><article className="card span-6"><h2>Статус процесса</h2><p>Очередь: {heartbeat?.queue_size??'—'}</p><p>Получено: {heartbeat?.received_messages??'—'} · с ключевыми словами: {heartbeat?.keyword_matches??'—'} · сохранено: {heartbeat?.saved_matches??'—'}</p><p className="muted">Обновлено: {heartbeat?.updated_at?new Date(heartbeat.updated_at).toLocaleString('ru-RU'):'нет данных'}</p></article><article className="card span-6"><h2>История операций</h2>{dashboard?.operations.length?<ul>{dashboard.operations.map((item,index)=><li key={`${item.at}-${index}`}>{new Date(item.at).toLocaleString('ru-RU')} — {item.event}{item.action?`: ${item.action}`:''}</li>)}</ul>:<p className="muted">Операций пока нет</p>}</article></section>{pending&&<ConfirmAction title={actionText[pending][0]} description={actionText[pending][1]} onConfirm={doAction} onCancel={()=>setPending('')}/>}</main>;
}
